#!/bin/bash

# Quick Deployment Guide for BitFlow Contracts
# =============================================

echo "🚀 BitFlow Contract Deployment - Quick Guide"
echo "=============================================="
echo ""

ACCOUNT_ADDRESS="0x20709f2d7a233345ed3e17ae2f2bf7d8e78598f1aa737b82e85ade052e00ddd"

echo "📋 Step 1: Fund Your Account"
echo "----------------------------"
echo "Account Address: $ACCOUNT_ADDRESS"
echo ""
echo "Option A - Starknet Faucet (STRK tokens):"
echo "  1. Visit: https://starknet-faucet.vercel.app/"
echo "  2. Paste address: $ACCOUNT_ADDRESS"
echo "  3. Complete CAPTCHA"
echo "  4. Click 'Request 100 STRK'"
echo "  5. (Optional) Connect GitHub for 800 STRK"
echo ""
echo "Option B - Blast API Faucet:"
echo "  Visit: https://blastapi.io/faucets/starknet-sepolia-eth"
echo ""
echo "Option C - Alchemy Faucet:"
echo "  Visit: https://www.alchemy.com/faucets/starknet-sepolia"
echo ""

echo "⏳ Step 2: Wait for Account Deployment"
echo "--------------------------------------"
echo "The deployment script is already running and will:"
echo "  • Detect when funds arrive (checks every 5 seconds)"
echo "  • Automatically deploy the account contract"
echo "  • Update .env with the correct account address"
echo ""

echo "🔧 Step 3: Deploy Contracts (Automatic)"
echo "---------------------------------------"
echo "After account deployment completes, run:"
echo "  node scripts/deploy-scarb.js"
echo ""
echo "This will deploy:"
echo "  1. WrappedBTC (ERC20 token)"
echo "  2. InvoiceRegistry (invoice management)"
echo "  3. Escrow (secure payments)"
echo "  4. Link Escrow to InvoiceRegistry"
echo ""

echo "✅ Step 4: Verify & Test"
echo "-----------------------"
echo "After deployment:"
echo "  • Mint test tokens: npm run mint-tokens setup"
echo "  • Start backend: npm start"
echo "  • Run demo: npm run demo"
echo ""

echo "📊 Current Status"
echo "----------------"
echo "✅ Contracts compiled"
echo "✅ Deployment scripts ready"
echo "⏳ Waiting for account funding..."
echo ""
echo "Copy this address to the faucet:"
echo "$ACCOUNT_ADDRESS"
echo ""
